In [1]:
import sympy as sp
import numpy as np
from scipy.integrate import quad
from numpy import exp, log, inf, e
from sympy import init_printing
init_printing()
from fractions import Fraction

In [2]:
A_b = sp.Matrix([[1,1,1,1],[1/2,-2/3,1/4,0],[1/4,1/3,-3/4,0]])
A_b

⎡ 1            1             1    1⎤
⎢                                  ⎥
⎢0.5   -0.666666666666667  0.25   0⎥
⎢                                  ⎥
⎣0.25  0.333333333333333   -0.75  0⎦

In [3]:
A_b.rref()

⎛⎡1  0  0  0.350877192982456⎤           ⎞
⎜⎢                          ⎥           ⎟
⎜⎢0  1  0  0.368421052631579⎥, (0, 1, 2)⎟
⎜⎢                          ⎥           ⎟
⎝⎣0  0  1  0.280701754385965⎦           ⎠

In [4]:
A = sp.Matrix([[1/4,1/2,1/4],[1/3,1/3,1/3],[1/2,1/4,1/4]])
B = sp.Matrix([[1,0,0]])
B@A**4

[0.350549768518518  0.368778935185185  0.280671296296296]

In [5]:
A = sp.Matrix([[1/4,1/2,1/4],[1/3,1/3,1/3],[1/2,1/4,1/4]])
B = sp.Matrix([[1,0,0]])
B

[1  0  0]

In [6]:
C = sp.Matrix([[1/8,3/8,3/8,1/8],[1/4,1/2,1/4,0],[1/2,1/2,0,0],[1,0,0,0]])
C

⎡0.125  0.375  0.375  0.125⎤
⎢                          ⎥
⎢0.25    0.5   0.25     0  ⎥
⎢                          ⎥
⎢ 0.5    0.5     0      0  ⎥
⎢                          ⎥
⎣  1      0      0      0  ⎦

In [7]:
C.T.eigenvals()

In [8]:
import scipy.linalg
H= sp.matrix2numpy(C).astype(float)
v,l=scipy.linalg.eig(H,right=False,left=True)
pi = l[:,0]/sum(l[:,0])
pi

array([0.2962963 , 0.44444444, 0.22222222, 0.03703704])

In [9]:
A=sp.Matrix([[-7/8,1/4,1/2,1,0],[3/8,-1/2,1/2,0,0],[3/8,1/4,-1,0,0],[1,1,1,1,1]])
A.rref()[0][:,4]

⎡0.296296296296296⎤
⎢                 ⎥
⎢0.444444444444444⎥
⎢                 ⎥
⎢0.222222222222222⎥
⎢                 ⎥
⎣0.037037037037037⎦

In [10]:
A.rref()[0][:,4].T@C**3

[0.296296296296296  0.444444444444444  0.222222222222222  0.037037037037037]

In [11]:
C

⎡0.125  0.375  0.375  0.125⎤
⎢                          ⎥
⎢0.25    0.5   0.25     0  ⎥
⎢                          ⎥
⎢ 0.5    0.5     0      0  ⎥
⎢                          ⎥
⎣  1      0      0      0  ⎦

In [12]:
(sp.Matrix([[1,0,0,0]])@C**3)

[0.244140625  0.439453125  0.263671875  0.052734375]

In [51]:
import scipy.linalg

m=52
P = sp.Matrix(np.ones((m,m))*1/(m-1)-np.eye(m)*1/(m-1))
P = sp.matrix2numpy(P).astype(float)

P= np.array([[0,0.25,0.25,0.25,0.25],[1,0,0,0,0],[0,1,0,0,0],[0,0,1,0,0],[0,0,0,1,0]])
P


array([[0.  , 0.25, 0.25, 0.25, 0.25],
       [1.  , 0.  , 0.  , 0.  , 0.  ],
       [0.  , 1.  , 0.  , 0.  , 0.  ],
       [0.  , 0.  , 1.  , 0.  , 0.  ],
       [0.  , 0.  , 0.  , 1.  , 0.  ]])

In [52]:
import scipy.linalg
v,l=scipy.linalg.eig(P,right=False,left=True)

for i in range(len(v)):
    if all(abs(l[:,i])<1):
        if sum(l[:,i])==1:
            pi = l[:,i]
            break
pi

array([0.20930233, 0.27906977, 0.27906977, 0.23255814])

In [72]:
P_4 = P[:4,:4]
P_3 = np.delete(P,3,0)
P_3 = np.delete(P_3,3,1)
(np.linalg.inv(np.eye(4)-P_3)[0,:]).sum()

In [71]:
(np.linalg.inv(np.eye(4)-P_4)[0,:]).sum()

In [73]:
P_2 = np.delete(P,2,0)
P_2 = np.delete(P_2,2,1)
(np.linalg.inv(np.eye(4)-P_2)[0,:]).sum()

In [15]:
P=np.matrix([[1/3,2/3,0,0],[1/2,0,1/2,0],[0,1/2,0,1/2],[0,0,3/5,2/5]])
P

matrix([[0.33333333, 0.66666667, 0.        , 0.        ],
        [0.5       , 0.        , 0.5       , 0.        ],
        [0.        , 0.5       , 0.        , 0.5       ],
        [0.        , 0.        , 0.6       , 0.4       ]])

In [16]:
pi_0=np.matrix([[0,0,1,0]])
(pi_0@(P**4))

matrix([[0.24861111, 0.11555556, 0.43383333, 0.202     ]])

In [17]:
v,l=scipy.linalg.eig(P,right=False,left=True)
pi=l[:,2]/sum(l[:,2])
pi

array([0.20930233, 0.27906977, 0.27906977, 0.23255814])

In [18]:
green = (np.eye(3)-np.array([[1/3,2/3,0],[1/2,0,1/2],[0,1/2,0]]))
sp.Matrix(green).inv()

⎡4.5  4.0  2.0⎤
⎢             ⎥
⎢3.0  4.0  2.0⎥
⎢             ⎥
⎣1.5  2.0  2.0⎦