In [4]:
import sympy as sp
import numpy as np
from scipy.integrate import quad
from numpy import exp, log, inf, e
from sympy import init_printing
init_printing()
from fractions import Fraction

In [67]:
A_b = sp.Matrix([[1,1,1,1],[1/2,-2/3,1/4,0],[1/4,1/3,-3/4,0]])
A_b

⎡ 1            1             1    1⎤
⎢                                  ⎥
⎢0.5   -0.666666666666667  0.25   0⎥
⎢                                  ⎥
⎣0.25  0.333333333333333   -0.75  0⎦

In [68]:
A_b.rref()

⎛⎡1  0  0  0.350877192982456⎤           ⎞
⎜⎢                          ⎥           ⎟
⎜⎢0  1  0  0.368421052631579⎥, (0, 1, 2)⎟
⎜⎢                          ⎥           ⎟
⎝⎣0  0  1  0.280701754385965⎦           ⎠

In [69]:
A = sp.Matrix([[1/4,1/2,1/4],[1/3,1/3,1/3],[1/2,1/4,1/4]])
B = sp.Matrix([[1,0,0]])
B@A**4

[0.350549768518518  0.368778935185185  0.280671296296296]

In [70]:
A = sp.Matrix([[1/4,1/2,1/4],[1/3,1/3,1/3],[1/2,1/4,1/4]])
B = sp.Matrix([[1,0,0]])
B

[1  0  0]

In [217]:
C = sp.Matrix([[1/8,3/8,3/8,1/8],[1/4,1/2,1/4,0],[1/2,1/2,0,0],[1,0,0,0]])
C

⎡0.125  0.375  0.375  0.125⎤
⎢                          ⎥
⎢0.25    0.5   0.25     0  ⎥
⎢                          ⎥
⎢ 0.5    0.5     0      0  ⎥
⎢                          ⎥
⎣  1      0      0      0  ⎦

In [226]:
C.T.eigenvals()

In [234]:
import scipy.linalg
H= sp.matrix2numpy(C).astype(float)
v,l=scipy.linalg.eig(H,right=False,left=True)
pi = l[:,0]/sum(l[:,0])
pi

array([0.2962963 , 0.44444444, 0.22222222, 0.03703704])

In [183]:
A=sp.Matrix([[-7/8,1/4,1/2,1,0],[3/8,-1/2,1/2,0,0],[3/8,1/4,-1,0,0],[1,1,1,1,1]])
A.rref()[0][:,4]

⎡0.296296296296296⎤
⎢                 ⎥
⎢0.444444444444444⎥
⎢                 ⎥
⎢0.222222222222222⎥
⎢                 ⎥
⎣0.037037037037037⎦

In [188]:
A.rref()[0][:,4].T@C**3

[0.296296296296296  0.444444444444444  0.222222222222222  0.037037037037037]

In [198]:
C

⎡0.125  0.375  0.375  0.125⎤
⎢                          ⎥
⎢0.25    0.5   0.25     0  ⎥
⎢                          ⎥
⎢ 0.5    0.5     0      0  ⎥
⎢                          ⎥
⎣  1      0      0      0  ⎦

In [199]:
(sp.Matrix([[1,0,0,0]])@C**3)

[0.244140625  0.439453125  0.263671875  0.052734375]

In [211]:
m=5

In [216]:
sp.Matrix(np.ones((m,m))*1/m-np.eye(m)*1/m).left_eigenvects()

[(-0.2, 1, [[0.788675134594813  -0.211324865405187  -0.577350269189626  9.3037
1831805656e-65  0]]), (0.8 + 1.9750104650351e-128⋅ⅈ, 1, [[-0.447213595499958 +
 9.15838504262051e-65⋅ⅈ  -0.447213595499958 + 9.15838504262051e-65⋅ⅈ  -0.44721
3595499958 + 9.15838504262051e-65⋅ⅈ  -0.447213595499958 + 9.15838504262051e-65
⋅ⅈ  -0.447213595499958 + 9.15838504262051e-65⋅ⅈ]]), (-0.2 - 2.19455920039956e-
65⋅ⅈ, 1, [[0.00382332236803214 - 0.0144383070002921⋅ⅈ  0.322346366056672 - 0.6
41244390063955⋅ⅈ  -0.324497156278856 + 0.390892796234923⋅ⅈ  0.208179923507597 
- 0.121970645534198⋅ⅈ  -0.209852455653445 + 0.386760546363522⋅ⅈ]]), (-0.2 - 4.
50072943985681e-65⋅ⅈ, 1, [[0.248360481933461 + 0.646885487231821⋅ⅈ  0.27202179
7743724 - 0.959300434124025⋅ⅈ  -0.0197695584219926 - 0.381761550894891⋅ⅈ  0.23
7517583584122 + 0.61372913766919⋅ⅈ  -0.738130304839314 + 0.0804473601179058⋅ⅈ]
]), (-0.2 + 1.13329300817144e-64⋅ⅈ, 1, [[0.52258972086738 + 0.0756309802097889
⋅ⅈ  0.415604016643602 + 0.231010082374813⋅ⅈ  -0.1557